# Header
menu:
  Home: /
  Archives: /archives
  Tags: /tags/index.html
  About: /about.html


rss: /atom.xml

# Content
excerpt_link: 继续阅读
next_post: 下一篇
prev_post: 上一篇

# duoshuo
duoshuo: true

# display widgets at the bottom of index pages (pagination == 2)
# index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
show_count: false

# Miscellaneous

favicon: /favicon.png



less:
  compress: false
  paths:
    - css
