# Header navgation menu,
# displayed on the top header and the bottom footer
menu:
  Home: /
  Archives: /archives/index.html
  Tags: /tags/index.html
  About: /about.html


# impression words,
# this displays on homepage
impression: 「倘只看书   <br>   便变成书橱」 

#GitHub: https://github.com/vankai



rss: /atom.xml

# Your Email, 
# this display on the footer
email: mr.taokai@foxmail.com


# prefetch control
prefetchControl: true

# prefetch some sites' dns ,shorten your request's
prefetch:
  - https://github.com
  - https://www.heitaov.cn
# pre-render !this will spend many resource
preRender:
  - /archives/index.html
  - /tags/index.html
  - https://github.com/vankai/
  - https://www.heitaov.cn

# Content translation
#excerpt_link: ◇ 查看全文 ◇
excerpt_link: Read More
next_post: 下一篇
prev_post: 上一篇

# Duoshuo
duoshuo: true

# widget behavior
# control the archives's page
archive_type: 'yearly'
show_count: false

# Site's icon
favicon: /favicon.ico
