# Header
menu:
  Home: /
  Archives: /archives
  Tags: /tags/index.html
  GitHub: https://github.com/vankai
  About: /about.html




rss: /atom.xml


# prefetch control
prefetchControl: true

# prefetch some sites' ip
prefetch:
  - https://github.com
  - https://heitaov.cn

# pre-render !this will spend many resource
preRender:
  - /archives/
  - /tags/

# Content
excerpt_link: ◇ 查看全文 ◇
next_post: 下一篇
prev_post: 上一篇

# duoshuo
duoshuo: true

# display widgets at the bottom of index pages (pagination == 2)
# index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
show_count: false

# Miscellaneous

favicon: /favicon.ico


less:
  compress: true
  paths:
    - css
