# Header navgation menu,
# displayed on the top header and the bottom footer
menu:
  Home: /
  Archives: /archives/index.html
  Tags: /tags/index.html
  About: /about.html



#GitHub: https://github.com/vankai


rss: /atom.xml

# Site's icon
favicon: /favicon.ico

