# Header navgation menu,
# displayed on the top header and the bottom footer
menu:
  Home: /
  Archives: /archives/index.html

slogan: Stay hungry, <br>Be wise.
#GitHub: https://github.com/vankai


rss: /atom.xml

# Site's icon
favicon: /favicon.ico

